<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>HollowKnightLocal8StagFix</AssemblyName>
    <RootNamespace>KO.HollowKnight8.StagFix</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HollowKnight.GameLibs" Version="1.0.0-hollowknight.1.5.78.11833.api77" PrivateAssets="all" />
  </ItemGroup>
</Project>